### ISSUE TITLE
captionText should be added regardless of options

### ISSUE THREAD

**Issue by ubbeK** [Juicy/juicy-select#2]
If `options` is null or empty, the current feature in juicy-select is to ignor `captionText` whether it is set or not. The desired functionality is that it should be added regardless of `options`.

I had to change the code bellow

``` javascript
if (!this.options || !this.options.length) {
    this.$select.innerHTML = "";
    return;
}

if (!this.multiple && this.captionText) {
    this.$select.innerHTML = "<option value=''>" + this.captionText + "</option>";
}
```

to this

``` javascript
if (!this.multiple && this.captionText) {
    this.$select.innerHTML = "<option value=''>" + this.captionText + "</option>";
} else if (!this.options || !this.options.length) {
    this.$select.innerHTML = "";
    return;
}
```

in order for juicy-select to behave according to the description.

**Comment by miyconst** [comment]
Can you do this change, make sure that example page still works, and release a new `0.0.3` version?

**Comment by ubbeK** [comment]
@miyconst: Sure!

**Comment by ubbeK** [comment]
Fix has been pushed to master and tag pushed to **0.0.3**
