### ISSUE TITLE
View-model is not updated with initial value from value attribute in juicy-select

### ISSUE THREAD

**Issue by PatrykSzwer** [Juicy/juicy-select#22]
Related issue: https://github.com/Starcounter/Blending/issues/169

I'm using `juicy-select` in BlendingEditor like this:
```
                            <juicy-select value="{{model.ChoosenLayoutKey$}}" options="{{model.Layouts}}" text-property="Name" value-property="Key">
                                <select class="blendingeditor-select">
                                </select>
                            </juicy-select>
```

![image](https://user-images.githubusercontent.com/25042256/38608218-0cf1d0de-3d7b-11e8-9c00-5b44ab28793c.png)

As you can see the initial option that is showing up is the first layout (in this case LoginLayout). 
Intuitive behavior would be, that `model.ChoosenLayoutKey` should also have an initial value, same as the client sees, but right now (if not set by a server) this value is empty.

I think that what client sees should be matching what view-model has to avoid misleading, so my suggestion is to set property in `value` attribute with initial value when juicy-select is created.

**Comment by alshakero** [comment]
I think this is the correct behaviour. I don't think it makes sense for an element to change anything in the view model when it's mounted. As in initial state, value should affect the element, not the element should affect the value.

The initial value should be set on the server. I'll close but feel free to re-open if you agree.
