### ISSUE TITLE
Fix empty options behavior

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-select#3]
@ubbeK please read my comment for the commit: https://github.com/Juicy/juicy-select/commit/cc4705b53cab6428ac808afd8d72c23d7da46274.

**Comment by ubbeK** [comment]
@miyconst: Could you please review code before I change version and start working on [integration](https://github.com/HRidge/PalmaDoc/issues/23)

**Comment by miyconst** [comment]
Added some comments: https://github.com/Juicy/juicy-select/commit/e9d740842f5a68fb07f1b3c972ee946fbbaa8c5e

After fixes make sure that the demo page works.

**Comment by miyconst** [comment]
Online demo is available here: http://juicy.github.io/juicy-select/index.html.

**Comment by ubbeK** [comment]
Updated and merged to default branch + tag 0.0.4

**Comment by miyconst** [comment]
It looks like you did not push the tags.

**Comment by ubbeK** [comment]
tag 0.0.4 pushed correctly
