### ISSUE TITLE
Extend readme - purpose of using juicy-select

### ISSUE THREAD

**Issue by mmnosek** [Juicy/juicy-select#4]
Every time I'm using juicy-select I wonder what is a purpose of using it instead of plain HTML select. In general - normal select doesn't work properly. Can we add to readme some details why somebody should use it instead of standard one? For me - it is actually hard to find out. WDYT @miyconst?

**Comment by warpech** [comment]
Ping @miyconst - could you add to README information why `juicy-select` is preferable over `select`?

**Comment by miyconst** [comment]
@warpech thank you for the ping. The `readme` is updated now.

**Comment by warpech** [comment]
Perfect, thank you!
