### ISSUE TITLE
Array observer not working properly

### ISSUE THREAD

**Issue by aloscha** [Juicy/juicy-select#5]
Seems that array property observer doesn't work properly:
`options: { type: Array, value: [], observer: "optionsChanged" },`

After options change dynamically the observer method doesn't fired. Based on polymer documentation https://www.polymer-project.org/1.0/docs/devguide/observers#array-observation
I've change it into:
`properties: {
                options: { type: Array, value: [], notify: true },
            },`
        `observers: [
        'optionsChanged(options.*)'
       ]`

And that works for me

**Comment by tomalec** [comment]
:+1: AFAIK, that's the way it should be done

**Comment by warpech** [comment]
@tomalec do you remember what you meant in the above comment? That it should be fixed in `juicy-select` or that it's a __won't fix__?

**Comment by tomalec** [comment]
I mean "That it should be fixed in `juicy-select`" as proposed in OP

**Comment by warpech** [comment]
This looks very true.

@alshakero could you please take this when PR #9/#10 is finished?

**Comment by alshakero** [comment]
Of course!

**Comment by warpech** [comment]
@alshakero could you pls check if this might still be relevant since PR #10 was released?

**Comment by alshakero** [comment]
Yes, it's on my radar.

**Comment by alshakero** [comment]
PR in https://github.com/Juicy/juicy-select/pull/13

**Comment by alshakero** [comment]
Fixed in #13

**Comment by warpech** [comment]
Closing as done

**Comment by alshakero** [comment]
This is now tested against and released https://github.com/Juicy/juicy-select/releases/tag/1.1.1
